// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TerminalFrame {
  final int rows;
  final int cols;
  final List<String> lines;
  final Uint32List fgColors;
  final Uint32List bgColors;
  final Uint16List flags;
  final int cursorX;
  final int cursorY;
  final bool isClosed;

  const TerminalFrame({
    required this.rows,
    required this.cols,
    required this.lines,
    required this.fgColors,
    required this.bgColors,
    required this.flags,
    required this.cursorX,
    required this.cursorY,
    required this.isClosed,
  });

  @override
  int get hashCode =>
      rows.hashCode ^
      cols.hashCode ^
      lines.hashCode ^
      fgColors.hashCode ^
      bgColors.hashCode ^
      flags.hashCode ^
      cursorX.hashCode ^
      cursorY.hashCode ^
      isClosed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalFrame &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          cols == other.cols &&
          lines == other.lines &&
          fgColors == other.fgColors &&
          bgColors == other.bgColors &&
          flags == other.flags &&
          cursorX == other.cursorX &&
          cursorY == other.cursorY &&
          isClosed == other.isClosed;
}
